### ISSUE TITLE
Update app name in readme

### ISSUE THREAD

**Issue by biskyt** [openeyes/DicomProcessor#23]
The readme says that the compiled file will be named "app.bat" for Windows, or "app" for linux.

as far as I can see, the file is named dicomEngine.bat or dicomEngine. The readme needs to be updated with correct names.

**Comment by justulka** [comment]
@biskyt 
Fixed in https://github.com/openeyes/DicomProcessor/commit/2389d569a9d37009e1b3f3cbc3a082da0055a5c6
